### ISSUE TITLE
Os assets não aparecem mais em modo production

### ISSUE THREAD

**Issue by heliohead** [upme-app/upmeapp#1]
Pretendo contribuir com o projeto, preciso saber, qual a versão de ruby, no Gemfile tem comentado 2.3.0, é isso mesmo?, onde é feito o deploy AWS, Heroku, DO?

**Comment by paulorja** [comment]
conseguimos corrigir ontem, vou criar uma documentação pra rodar o projeto.

mas só pra responder suas perguntas
a versão do ruby é 2.3.0
o deploy é feito no heroku

**Comment by heliohead** [comment]
Blz, qq coisa abre outra issue e me marca :)
