### ISSUE TITLE
Envio de emails assíncronos

### ISSUE THREAD

**Issue by paulorja** [upme-app/upmeapp#7]
Adicionar o sidekiq para envio de emails assíncronos.

**Comment by heliohead** [comment]
Posso pegar esta, se puder entregar até quinta

**Comment by paulorja** [comment]
Pode sim, seria muito legal. A nossa equipe aqui usa o Trello pq eu sou o unico dev. Minhas tarefas estao todas la.


Se precisar eu posso listar os emails.

Estou disparando assim: Thread.new { Email.deliver }

**Comment by paulorja** [comment]
Já funcionando em produção. Muito obrigado!

**Comment by heliohead** [comment]
👍 O que tem que fazer agora é retirar todos os Thread.new e trocar os .deliver por .deliver_later

**Comment by paulorja** [comment]
aham, acho que já mudei todos aqui
