### ISSUE TITLE
Cadastro de Empresas/ONG

### ISSUE THREAD

**Issue by heliohead** [upme-app/upmeapp#8]
O form de cadastro para empresas/ong  esta faltando o campo "nome_empresa"
![screenshot 2017-10-09 09 15 23](https://user-images.githubusercontent.com/675604/31337719-f52764c0-acd2-11e7-8b88-d2ec58a9528b.png)

**Comment by paulorja** [comment]
Ainda estamos estudando sobre isso, talvez a gente adicione o telefone ai tambem.
 
Vou conversar com a equipe pra ver se eles tem interesse de fazer essa mudanca.

**Comment by paulorja** [comment]
@heliohead, eu e @salatielq estamos trabalhando nisso agora

![cadastro_04 3](https://user-images.githubusercontent.com/12129241/31678765-e72e1018-b34d-11e7-89ee-e1593d00ea1a.png)
